language: node_js
node_js:
  - "10"

before_install:
  - npm install -g grunt-cli

install:
  - yarn install

cache:
  yarn: true
  directories:
    - "node_modules"

before_script:
  - rm pelican-theme
  - mkdir -p pelican-theme/static/css
  - mkdir -p pelican-theme/static/js
  - mkdir -p pelican-theme/templates

script: grunt

branches:
  only:
    - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  target-branch: theme
  committer-from-gh: true
  local-dir: "./pelican-theme"
  on:
    branch: master
