language: node_js
node_js:
  - "10"

before_install:
  - npm install -g grunt-cli
  - npm install -g bower

install:
  - npm install
  - bower install

cache:
  directories:
    - "node_modules"
    - "bower_components"

before_script:
  - rm pelican-theme
  - mkdir -p pelican-theme/static/css
  - mkdir -p pelican-theme/static/js
  - mkdir -p pelican-theme/templates

script: grunt

branches:
  only:
    - master
